name: Deploy on Github Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    
    steps:
  - uses: actions/checkout@v2
  - name:Checkout
    uses: actions/setup-node@v2
    with:
      node-version: ${{ matrix.node-version }}
  - name: npm ci, build and test
    run: |
      npm ci
      npm run build --if-present
      npm run test -- --watchAll=false

